name: Docker Build and Push to Docker Hub

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_REPO: ysoliveira/portifolio

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract Docker metadata (tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_HUB_REPO }}
          tags: |
            latest
            v${{ github.run_number }}

      # 4. Build e Push da imagem Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: meu-portfolio/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
