# Nome da sua pipeline/workflow
name: Docker Build and Push to Docker Hub

# Define quando o workflow será executado
on:
  push:
    branches:
      - main

# Define as variáveis de ambiente que serão usadas globalmente no workflow
env:
  DOCKER_HUB_REPO: ysoliveira/portifolio

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # NOVO PASSO: Configurar o Docker Buildx
      # Este passo é crucial para habilitar o cache GHA
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Usa o driver 'docker' para criar um builder,
          # mas o 'setup-buildx-action' configura ele para suportar o cache GHA
          driver: docker

      - name: Extract Docker metadata (tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_HUB_REPO }}
          tags: |
            latest
            v${{ github.run_number }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: meu-portfolio/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Certifique-se que o cache-from e cache-to estão usando o escopo correto
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max